### ISSUE TITLE
How to set disabled after form is initialized?

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#135]
How can the disabled value of all fields be set _after_ the form has been initialized?

```
      const form = new MobxReactForm({ fields, plugins })

      const setDisabled = (value) => {
         // Do something with form and all its fields...
      }
```

**Comment by foxhound87** [comment]
If I correctly understood your question, 
you want to set `disabled` property for all fields in one shot?  

This can be done for example into the [**onInit()** Handler](https://foxhound87.github.io/mobx-react-form/docs/events/extending-form.html)

If you want to set the `disabled` prop to `true` for one specific field you can do:

``` javascript
class MyForm extends MobxReactForm {

  onInit(form) {

    form.$('field').set('disabled', true);
  }
}
```

If you want to set the `disabled` prop to `true` for all fields and nested fields:

``` javascript
class MyForm extends MobxReactForm {

  onInit(form) {

    form.forEach(field => field.set('disabled', true));
  }
}
```

I will document it asap because `forEach()` is missing on the docs right now.

Hope it will help.

**Comment by foxhound87** [comment]
FYI the documentation is updated. 

Please let me know if this helped or you need something else.

This can be useful for others users too.

Thank You.

**Comment by foxhound87** [comment]
I close this question, It can be found here:

https://foxhound87.github.io/mobx-react-form/docs/faq.html
