### ISSUE TITLE
extend() using prototype

### ISSUE THREAD

**Issue by anotherpit** [foxhound87/mobx-ajv-form#151]
`Form` and `Field` classes share a bunch of methods. Currently they are scattered among three different files, and are being created and applied to each new instance using `extend()` method. Why not just put them into common base class? I also believe, inheritance gonna be slightly more efficient, because methods are put on prototypes once and for all. @foxhound87, what do you think? Perhaps, I will be able to provide PR for this.

**Comment by foxhound87** [comment]
I haven't used "regular inheritance" because I'm following the **composition over inheritance** principle instead. 

I separated the methods in more objects to have more control (since the classes was growing, and now Form and Fields classes contains only their own methods).  I don't see the advantage to have common classes for these 3 files (or one big class of methods). 

With composition we can split the methods in different files and use it in different classes. 
I think with this pattern we have more flexibility, and each file can represent what actually does.

The use of the inheritance does not fit for all situation, but is indeed useful in some cases, like extending the main Form class for creating new forms instances.

What I want to fix instead, is the need to pass the `form` object into others object like the `Field` or `Validator`, but there are some functionalities that still depends on that.

**Comment by foxhound87** [comment]
For example, we can remove internal state from the `FieldParser` methods and make them not accessible form the `Form` and `Field` instances.

**Comment by anotherpit** [comment]
> I haven't used "regular inheritance" because I'm following the composition over inheritance principle instead.

OK, got it. 

> With composition we can split the methods in different files and use it in different classes. 
> I think with this pattern we have more flexibility, and each file can represent what actually does.

Kind of. But the one thing that really bothers me is that these three files actually depend on each other. `FieldHelpers` calls `initFields()` defined in `FieldInit`. `FieldInit` calls `select()` defined in `FieldHelpers`. `FieldParser` relies on `$this.state` and `$this.validator` which are only defined in end-user classes. In other words, one cannot use, for example, `FieldHelpers` without using `FieldInit`. Thus, these files do not really represent separate pieces of functionality, they rather represent some one big piece of functionality and scatter its implementation among several places. BTW, that also makes it harder to search the necessary method in the project.

---

And now to the main point. Regardless of whether they stay three different files or become one big file, and whether we use inheritance or no, I propose that those methods should rather be applied to the prototypes, not instances. Currently, every time some new instance of the `Form` or `Field` class is being created, `extend()` method creates a whole bunch of these methods anew allocating them in the memory, etc. `form1.select !== form2.select`. I think we should put them into prototypes once and for all. Assuming we refactor each mixin file to return a collection of methods instead of the function that applies them, it gonna look like this:

``` js
class Form {
   // ...
}
Object.assign(Form.prototype, FieldParser);
Object.assign(Form.prototype, FieldHelpers);
Object.assign(Form.prototype, FieldInit);
```

**Comment by foxhound87** [comment]
It's ok form me to use the prototype approach, 
if you say it will reduce memory usage, let's do it!
