### ISSUE TITLE
Support for older browsers - Babel polyfills

### ISSUE THREAD

**Issue by luthv** [foxhound87/mobx-ajv-form#171]
Is there any plan to support IE11?

Currently the library failed with some unsupported language features such as Object.assign and Promise.

**Comment by foxhound87** [comment]
It's not a priority to support those polyfills out of the box right now.

This because maybe some devs would like to have support only for evergreen browsers and saving bundle size. 

Anyway I think you can fix it yourself using babel polyfills:
https://babeljs.io/docs/usage/polyfill/ 

you can compile it or add it to the browser scripts.

**Comment by luthv** [comment]
Thanks, I already did that. Anyway there's an unrelated problem with latest react and babel-polyfill for ie11 as described [here](https://github.com/facebook/react/issues/8379#issuecomment-263962787), I thought I leave it here, hopefully it will help people that encounter the same problem.
