### ISSUE TITLE
Unexpected behaviour when providing an initial value that is a number

### ISSUE THREAD

**Issue by levic92** [foxhound87/mobx-ajv-form#175]
Hello,

When a field is initialized with a value that is a number there is a bug and you can no longer set this field to anything other than a number. You can no longer type a decimal. Example: if the field is initialized with the number 4 you will not be able to change it to 4.5, you also cannot clear that field because when you clear the field it resets to 0. I believe this behaviour should be removed and it should be left to the validation libraries.

Here is the code causing the issue:
[https://github.com/foxhound87/mobx-react-form/blob/master/src/Field.js#L239-L246](url)
```js
...
    // handle numbers
    if (_.isNumber(this.$initial)) {
      const numericVal = _.toNumber(newVal);
      if (!_.isString(numericVal) && !_.isNaN(numericVal)) {
        this.$value = numericVal;
        return;
      }
    }
...
```

**Comment by foxhound87** [comment]
The idea was if the value is initialized with a number, it should remain a number, because for example, if you clear the field, it will became an empty string (instead should be zero).

About the decimal numbers, you can set them also afterwards, but I just noticed a bug, the fields doesn't accept the dot if you try to add it at the end of the value. If you try to add the dot in the middle of the value, it works.

I think is not good to merge your PR right now (which will remove this behavior completely), because it will break the current behavior for numbers for the users which are currently using the package, instead we should fix this and find a better types handling for the next major release. 

Give me some time to think about it so I can find a good way to fix it, otherwise we will reconsider your PR.

I was planning to implement a better types handling anyway (I want to introduce parser, formatter and normalizer too)

**Comment by foxhound87** [comment]
I think we can introduce a from option like `autoParseNumbers` and run that part of code only if this option is true.

**Comment by foxhound87** [comment]
If you don't want **zero** when the field is empty, pass the number as `string` when initialize the fields. You should be able to handle the numbers as strings and parse it to number afterwards.

**Comment by foxhound87** [comment]
Now with this fix https://github.com/foxhound87/mobx-react-form/commit/79bbe839a3e9de298bef53c4d4756a86c97b8c41 you should be able to set the decimals correctly. Let me know if you encounter other issue.

I will introduce `autoParseNumbers` option anyway to disable this behavior if you need.

**Comment by foxhound87** [comment]
`autoParseNumbers` option is now available (https://github.com/foxhound87/mobx-react-form/commit/6281645d7059d2e412227328a4c29aecb347156e).

The [option section](https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-options.html) on the docs is now updated. 

Now to disable this behavior you can do:

```javascript
const options = {
  autoParseNumbers: false,
};

new Form({ options, ... });
```

**Comment by levic92** [comment]
Thanks for adding that behaviour. Yes setting the initial value to a string is a work around for now. The following has been fixed:
- Cannot add a decimal to an existing number at the end of the value. (fixed with 79bbe83)

With the current implementation there are still a few bugs:
1. Maybe this isn't a bug, but is it the ideal behaviour? Cannot clear a number field. Even if this is a number field should there be an option to clear it instead of setting it to 0?
3. There is still one more bug with decimals even with the fix in 79bbe83. This won't handle for example: setting 4 to 4.02. toNumber changes 4.0 to 4 before you can add anything after the 0. toNumber will clear any zeros after the decimal place if it does not end with a number greater than zero.

**Comment by foxhound87** [comment]
1. Because if you want numeric values and when you get the value you expect to see a number, not en empty string. Otherwise you have to deal with it afterward if you need to make some computation with that value. 
2. Right, I will fix it, thank you for testing.

**Comment by levic92** [comment]
One more thing i noticed is that you cannot set a negative number

**Comment by foxhound87** [comment]
right, but only in some situation. I have to find a better way to handle values with `_.toNumber()`
