### ISSUE TITLE
How to reorder nested fields?

### ISSUE THREAD

**Issue by w-** [foxhound87/mobx-ajv-form#177]
This is more of a question.
In my form i have fields defined like

```
[
	'name',
	'list',
	'list[].name',
	'list[].blah',
]
```

What is the best way to reorder items in list? or even to do inserts into specific indexes of the list?

the only way i can think of right now is to make a call like
```
let foo = form.$('list').value;
/***
 do some reordering logic on foo as it is a basic javascript array of objects
 ***/ 
form.$('list').update(foo)
```
This seems less than optimal. Is there a better/recommended way to do this?

**Comment by foxhound87** [comment]
I have no plans to add ordering logic for the fields. You have to implement it yourself.

If you need to provide custom indexes, you can do it when add new fields using the `.add()` method as discussed on this issue: https://github.com/foxhound87/mobx-react-form/issues/169

The syntax is:
```javascript
form.$('myArrayField').add(fieldValue, { key: customKey });
```

I will update the docs because it seems to be missing.

**Comment by w-** [comment]
interesting. was not aware of this feature. Thanks for the quick response
