### ISSUE TITLE
Bindings Improvement Request

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#191]
Really happy to see the new 'bindings' feature - I had been working on the same idea.

I would like to suggest an improvement that slightly reduces typing and improves readability:

Instead of doing:

```jsx
       <Question
         question='Are you currently a student?'
         component={ YesNoRadioButtonGroup }
         { ...form.$('currentlyStudent').bind() } />
```

We could do:
```jsx
       <Question
         question='Are you currently a student?'
         component={ YesNoRadioButtonGroup }
         { ...form.currentlyStudent } />
```

Or, to prevent any field name collisions, we scope the fields under `form.bindings().currentlyStudent`.

Now usage is as simple as:

```jsx
const MyView = ({ form }) => {

       const f = form.bindings()

       <Question
         question='Are you currently a student?'
         component={ YesNoRadioButtonGroup }
         { ...f.currentlyStudent } />
}

```

Which has the added syntax benefit of being more 'pluggable', ie not specific to the mobx-react-form api that makes use of `$` and `bind()`.

**Comment by foxhound87** [comment]
There are some things to be considered. I don't think what you said can be done using a global `.bindings()` namespace with that code style, this because of the current code structure (on how fields are handled and selected) which now use the field selector $() and not a plain object notation, it is also very complex (because handles nested fields) and for achieve what you are asking I should replicate the whole fields structure into a bindings object with a significant amount of additional code, and this is something I want to avoid.

That said, you can avoid that creating custom components with a property which represents only the bindings or using the "||" operator to test the bind() method.

**Comment by liveresume** [comment]
I understand.  

Can you show an example for both:

> That said, you can avoid that creating custom components with a property which represents only the bindings or using the "||" operator to test the bind() method.

**Comment by foxhound87** [comment]
something like:

```javascript
export default observer(({ field = null, bindings = null }) => (
  <div>
    <input {...bindings || field.bind()} />
  </div>
));
```

In this manner you can pass your own bindings to the component or use the bind() method of the package if custom bindings are not provided. 

This is very simple and generic approach but should work for your case.
