### ISSUE TITLE
Nested Fields onAdd() errors when using Unified Properties

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#192]
I am having trouble using `f.$('collegeDegrees')onAdd()` when I build my fields like this:

```
const fields = {
  collegeDegrees: [{
    name: '',
    level: '',
    yearAttained: ''
  }]
}
```

Nothing seems to happen but some cryptic errors.

**Comment by foxhound87** [comment]
What's the error?

**Comment by foxhound87** [comment]
Anyway you provided a **separated** and not **unified** props definition.

So you should provide a **fields** object with the structure:

```javascript
const fields = [
  'collegeDegrees',
  'collegeDegrees[].name',
  'collegeDegrees[].level',
  'collegeDegrees[].yearAttained',
];
```

then your object as **values**:

```javascript
const values = {
  collegeDegrees: [{
    name: '',
    level: '',
    yearAttained: '',
  }],
};
````

Or using **unified** props definition, you should do:

```javascript
const fields = [{
  name: 'collegeDegrees',
  fields: [{
    name: 'name',
    value: '',
  }, {
    name: 'level',
    value: '',
  }, {
    name: 'yearAttained',
    value: '',
  }],
}];
```

**Comment by liveresume** [comment]
> ```
> const fields = [{
>   name: 'collegeDegrees',
>   fields: [{
>     name: 'name',
>     value: '',
>   }, {
>     name: 'level',
>     value: '',
>   }, {
>     name: 'yearAttained',
>     value: '',
>   }],
> }]
> ```

Now I understand. Thanks.

**Comment by foxhound87** [comment]
Can you post the error you got?

So I can try to make a better error handling and provide a more friendly error for this situation.

Thank You.

**Comment by liveresume** [comment]
I am having trouble selecting the nested fields using the unified props approach.
(nested + separated props work well)

```js
form.$('collegeDegrees').$('name') 

mobx.js:1284 [mobx] Catched uncaught exception that was thrown by a reaction or observer component,

 in: 'Reaction[Constructor#0.render()] Error: The selected field is not defined (name)(…)
```

FYI the nested fields are meant to be repeating.

The original problem had to do with mixing unified and separated, and flat and nested properties.  Maybe detect when an invalid mix is supplied?

**Comment by liveresume** [comment]
Also here is an update request.  Can we get a `setDeep(val)`?

Would work to toggle props like `disabled` and blank out `label` s.

```js
form.forEach( field => field.setDeep('label', ''))
```

**Comment by foxhound87** [comment]
If you have nested array of fields, you should provide an index key:

```javascript
form.$('collegeDegrees').$(n).$('name') 
```

because of this you get **"Error: The selected field is not defined (name)".**

It can depend on how you structured the fields in both unified/separated modes (maybe you described them differently, you cannot mix unified/separated).


If you need to operate on some branch of nested fields, you can also chain other [actions](https://foxhound87.github.io/mobx-react-form/docs/actions) to the selector.

For example selecting the `collegeDegrees` we can use **map()** or **forEach()** to iterate the nested fields or the **set()** method as well.

```javascript
form.$('collegeDegrees').forEach(field => {
   // use field
});
```

> **forEach()** will iterate **deep** nested fields automatically. 

Using it in conjunction with `set()` you can bulk-set fields props **deeply**:

```javascript
// set all fields & nested fields label to empty string
form.forEach(field => field.set('label', ''));
```

> **set()** will change only the current field props in this case (not provided object in input).

If you need to specify all fields props individually per field you do NOT need to use **deepSet()** but just use **set()** providing an object, for example in your case:

```javascript
    form.set('label', {
      collegeDegrees: [{
        name: '...',
        level: '...',
        yearAttained: '...',
      }, {
        name: '...',
        level: '...',
        yearAttained: '...',
      }],
    });
```

> **set()** will call automatically **deepSet()**  when needed as in this case.

You can provide plain object of nested fields without array as well.

I hope it will be helpful!
