### ISSUE TITLE
How to observe nested field addition

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#206]
I want to set an id on a nested field whenever a new nested field is added.
```js

fields = [ 'jobs', 'jobs[].id']

observe(form.fields.get('jobs'), '$value', () => {
  console.log('update')
})
```

But nothing happens when I add a job.

**Comment by foxhound87** [comment]
In your case you should observe `value` not `$value` because `value` is **computed** when you have array of fields. For this reason is always better to listen on `value` and not `$value`.

Remember that to get the `jobs` field you can just use `form.$('jobs')`.

So in your case just

```javascript
observe(form.$('jobs'), 'value', () => console.log('update'));
```

and to check events on the observable map itself you can do:

```javascript
form.$('jobs').fields.observe(data => console.log('changed', data));
```

**Comment by liveresume** [comment]
That worked to get updates.  However it fires on update of any nested field.  

My goal is to have it fire only when a new array element is added.  

And it should ideally also run when the form is first created and creates a single nested field by default, ie array index 0.

**Comment by foxhound87** [comment]
The `.fields.observe()` is what you need, It fires on `add`/`delete` of the observable map elements.
