### ISSUE TITLE
Possible reset() bug

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#207]
reset() docs say it should "Reset the Form to initial values."

I am trying to reset a nested field to its initial values which I set myself after a successful save.

```js
const model = form.$('jobs[0]')
model.set('initial', { name: 'something awesome' })

// Doing this clears the model instead of resetting to initial values.
model.reset()
```

**Comment by liveresume** [comment]
This seems to work well but for one thing:

```js
      model.forEach( field => {
          field.set('default', field.value)
      })

      model.reset() 
```

Looks like reset() is to defaults, not to initials.

Another possible bug: setting the initial of the nested field item at its own level does not propagate to its children.

**Comment by foxhound87** [comment]
Yes, the **reset()** method will set the `default` value and not the `initial` value;

I said **"Reset the Form to initial values"** because if you provide the `value` prop, it will become the `default` automatically when the form is created (if a `default` prop is not provided). I will clarify that on the docs.

So you should provide the `value` prop or `default` prop when defining fields on [Form Initialization](https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-initialization.html) (to the form **constructor** or the **setup()** method) and the reset() will work as expected.

Can you explain better what you mean for: "Another possible bug: setting the initial of the nested field item at its own level does not propagate to its children."

Thank You.

**Comment by liveresume** [comment]
For example if I do:

```js
const model = form.$('jobs[0]')
model.set('initial', { name: 'something awesome' })
```

The 'name' prop will not be set.  I have to select name and set it specifically.

```js
form.$('jobs[0].name').set('initial', 'something awesome')
```

**Comment by liveresume** [comment]
Actually, I need to update the default values dynamically; after form init.  
What is working for me now:

```js
const setValuesAsDefault = (model) => {
  model.forEach( field => {
    field.set('default', field.value)
  })
}

const resetValuesToDefaults = (model) => {
  // Resets to *default* values.
  model.reset()
}
```

**Comment by foxhound87** [comment]
`form.$('jobs[0].name').set('initial', 'something awesome')` is the correct one because you are trying to update the initial prop of a nested field (and not applying an object `{ name: 'something awesome' }` to the **jobs[0]** `initial` prop.

Alternatively if you provide the object you should use the `set()` method by the **Form** instance:

```javascript
form.set('initial', { jobs: { 0: { name: 'something awesome' } } })`
````

Normally the `default` prop will be defined by the `initial` prop or `value` prop or by the `default` prop itself when initializing the form.

If you are using separated props mode you can use:

```javascript
const defaults = {
   'jobs[].name': 'default value',
};
```

This will apply the defined defaults to new added array elements too.

I think you don't need `setValuesAsDefault()`. As said before, the `default` prop is inherited from the `value` prop. So you should have the `default` prop already defined.

Are you using the DevTools? Try it to inspect your fields structure and props.
