### ISSUE TITLE
Dynamic Fields: Create new Fields with add()

### ISSUE THREAD

**Issue by mattanbi** [foxhound87/mobx-ajv-form#240]
We use mobx-react-form for our forms. One of our forms has a multi select dropdown. according to the selection, fields are added / removed from the form. How can this be managed in mobx-react-form?

**Comment by foxhound87** [comment]
You should use the `.add()`/`.del()` methods if the fields are treated as array elements.

What's your fields structure and which fields you need to add/remove ?

**Comment by oferk1** [comment]
Our field structure is a select field, in which when choosing different options some text fields should appear and disappear accordingly.
Do you have a working demo of some kind for add & del ?

**Comment by foxhound87** [comment]
In the [Demo Repo](https://github.com/foxhound87/mobx-react-form-demo) you can find an example using the `onAdd(e)`/`onDel(e)` handlers, which are called from components.

Otherwise you can use [add() & del()](https://foxhound87.github.io/mobx-react-form/docs/actions/shared.html#add--del-nested-array-elements) methods where you need (for example when implementing custom Event Handlers or when [observing](https://foxhound87.github.io/mobx-react-form/docs/events/mobx-events.html) the Fields props)

**Comment by foxhound87** [comment]
Or maybe you need to create new fields after the form initialization. For doing this you can use the `initField(key)` method on **Form** or **Field** instances. This is not documented because I'm planning to integrate it into the `add()` method (which now supports only arrays elements).

**Comment by foxhound87** [comment]
Made a fix, now you can use `this.add('fieldValue', { key: 'fieldName' });` everywere.

**Comment by foxhound87** [comment]
@oferk1 I will make a demo with show/hide fields functionalities.

**Comment by oferk1** [comment]
Wonderful thanks, we are looking forward to it as we were unsure how to implement
