### ISSUE TITLE
Reset form back to pristine?

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [foxhound87/mobx-ajv-form#256]
After submitting the form and later on deciding that something is wrong anyway (i.e. call from server returned an error), is there a way to revert form back to pristine state, not showing errors? I've tried .clear() and reset(), but they don't seem to do the trick.

**Comment by foxhound87** [comment]
`reset()` should work. It will revert `isPristine` to `true`.

If you need to hide errors when the form `isPristine` is `true` you can use `showErrors(false)` with `observe`:

```javascript
import { observe } from 'mobx';

class MyForm extends Form {

  onInit() {
    observe(this, 'isPristine', change => 
      change.newValue && this.showErrors(false));
  }
}
```

For now this example is using the original mobx `observe` function.
I noticed that the package's `observe()/intercept()` methods have to be updated to support the forms properties.

**Comment by sebastian-zarzycki-apzumi** [comment]
But is there a way to revert form back to truly pristine state? I had a hard time figuring out what pristine means in the code, from what I could gather, it's a sum total of all fields comparisons against default value. In this light, whether clear() or reset() works depends on what the initial values actually were. 

But it doesn't take the fact that, i.e. form was already submitted. Maybe a method to truly "reset" everything (or at least methods to influence the submitted/pristine state) could be added?

"I noticed that the package's observe()/intercept() methods have to be updated to support the forms properties." - what do you mean by that?

**Comment by foxhound87** [comment]
What do you mean for "reset everything". What should be your desired state on "reset"? Using the form functionalities and options you can actually change the form behaviors. If you need to have a completely clear form, consider to not provide values to the constructor but use **init()** to initialize fields props/values instead. So the reset should do be a "complete" reset.

**Comment by sebastian-zarzycki-apzumi** [comment]
The pristine state should be the state that reverts all what form submitting changes.

**Comment by foxhound87** [comment]
The pristine state is the opposite of dirty, it means the original state without user interaction, in relation to the initial values (or default if provided)

**Comment by foxhound87** [comment]
I think we need to control the `showErrors()` tracking the **touched** prop which should be **false** on "reset" to a "pristine" state.

**Comment by foxhound87** [comment]
We have also a `showErrorsOnReset` **option** for the form which can be helpful in your case.

**Comment by benjamingeorge** [comment]
I have a use case where I want to use the isDirty property to show and hide a particular button on an "edit" form.  Meaning, hide the button if the form is dirty until they save the new edited form values. The problem is calling pristine after the form is successfully submitted resets the values to the non edited values.  Is there a way to set a form to a pristine state without resetting all the values ? I tried using an intermediary variable but MobxReactForm still has the dirty state.

**Comment by foxhound87** [comment]
@benjamingeorge 

The `isDirty` prop is not working properly in some cases and needs to be fixed.
I also will provide a method to set the current form values as initials, if I got your point.

**Comment by jkeruzec** [comment]
@foxhound87 Reading this issue, I'm trying to find a way to set back dirty to false on my form have been submitted (User enters form, dirty is false, user changed value, dirty is true, user submit/save form, dirty is now false again because form is in current new "database" state").

Can you provide this ?

 Thanks,
