### ISSUE TITLE
Validation changed from onKeypress to onBlur?

### ISSUE THREAD

**Issue by vstlouis** [foxhound87/mobx-ajv-form#266]
Hey there, great library by the way. Recently I am seeing that my form fields are only validating on blur (when i click out of the field rather than on change. Is this intended and or is there an option to validate onChange?

Thanks

**Comment by foxhound87** [comment]
The `validateOnBlur` is the new default behavior of the form. This is a design decision because for some users `validateOnChange` can be too annoying.

Anyway `validateOnChange` was not removed and can still be enabled using [Form Options](https://foxhound87.github.io/mobx-react-form/docs/form/form-options.html).

#### For all fields:

```javascript
const options = {
  validateOnChange: true,
};

new Form({ ... }, { options, ... });
```

#### Only for specific fields (in fields definitions):

```javascript
// UNIFIED MODE

const fields = {
  myField: {
    // other field props here
    options: {
      validateOnChange: true,
    }
  }
};

new Form({ fields });
```

```javascript
// SEPARATED MODE

const fields = [
  'myField'
];

const options = {
  'myField': {
    validateOnChange: true,
  },
};

new Form({ fields, options, ... });
```

**Comment by vstlouis** [comment]
Awesome, thank you. and great work by the way :1st_place_medal:

**Comment by foxhound87** [comment]
Thank You!
