### ISSUE TITLE
onSubmit gets triggered even if the form is invalid

### ISSUE THREAD

**Issue by sadasant** [foxhound87/mobx-ajv-form#281]
If a user changes a previously validated field, and directly clicks the submit button without causing the field to blur, the onSubmit function gets called automatically. Is this a bug?

**Comment by foxhound87** [comment]
The `onSubmit` Event Handler is always triggered when you click on the submit button, if you need to block the button if the whole form/fields are invalid, you can disable it implementing `isDisabledSubmit` function as explained  in #267

**Comment by sadasant** [comment]
Thanks!

**Comment by GabrielDelepine** [comment]
@sadasant this is probably because you put the onSubmit attribute on your button `<button onSubmit={this.onSubmit}>Hello</button>`

If you don't want the onSubmit function to be called when the form is invalid, you need to put it on the form element `<form onSubmit={this.onSubmit}>` and transform your button to a type submit one `<button type="submit">Hello</button>`

You will also need to use `preventDefault`
```
function onSubmit (event) {
event.preventDefault()
}
```
