### ISSUE TITLE
Is there a way to provide a custom validation message?

### ISSUE THREAD

**Issue by sadasant** [foxhound87/mobx-ajv-form#287]
I'm trying to customize fields to have a custom validation message, but I'm not finding a way to do it. Does that exists? If so, how could it be done? I'm up for making PRs! Just a quick direction on the right approach and I'll make a PR for it if y'all want 🙂

**Comment by althamash-chaipoint** [comment]
you can extend validations with custom functions or rules.
https://foxhound87.github.io/mobx-react-form/docs/validation/modes/vjf-custom.html

**Comment by foxhound87** [comment]
You can provide custom errors messages extending the **validation plugin** that you are using as discussed here https://github.com/foxhound87/mobx-react-form/issues/49 (where you can find an example with custom DVR messages). Using VJF is completely transparent because you can define a message for each validation rule. Or you can eventually use `.invalidate('a generic error message')` to invalidate a field and override the message.

**Comment by sadasant** [comment]
@foxhound87 @althamash-chaipoint yes!! Thank you both!
