### ISSUE TITLE
Validate Field with different Prop (validateWith) instead "value"

### ISSUE THREAD

**Issue by mdansei** [foxhound87/mobx-ajv-form#296]
Hi, I think adding a property to not validate if values are default is very useful, because a lot of times we deal with updating forms which usually have default values, so there's no point of validating.

Here's a scenario : 

you have a user profile form with default values, (e.g. value: 'SteveJobs') and one of the rules is checking if the user already exists with this name, this will trigger an error, even though this is the current username associated with that user.

So it would be handy to not validate if the values are equal to default values :)

**Comment by foxhound87** [comment]
I think the `onSuccess` should not be called if the value is the default, so the validation should occur normally, because for example if the username is used, you should not send the api request even tough the user is rewriting the same username. Or if the user makes a change with consequent api request then the default username will not match the database anymore. I think it's up to you make a check on the value/default and then hide/show a proper message on the `onError` function. Anyway, I have to think more about this, I'm not sure about this approach and should be elaborated more. Maybe it's more about not showing the validation errors.

**Comment by mdansei** [comment]
I see your point, but let's suppose `checkUser` rule is async, then this is done before `onSuccess ` is been called, the same happens with your mobx-demo repo. Eventually, I think it's kind of enhancement, and it would be great if you add a field prop to the `dvr` async rules as with `vjf` functions, if you want me to open an issue for it ;)

**Comment by foxhound87** [comment]
onSuccess/onError are always called after the sync/async validation process, what's the point here?

Can you elaborate more about "adding a field prop to the validators". Better if you can provide code examples of your case. Thanks.

**Comment by mdansei** [comment]
```
// vjf async validation 
export function checkUserAsync({field}) {  // this is what I mean by "field prop" 
    if (field.values() === field.defaults()) return true
    return checkUser(field.values(), field.key)
        .then(res => res.json())
        .then(res => [!res, msg])
}
```
I was using `dvr `async to do this, but I switched to `vjf` because it has a "field prop", so I can do a check if the value is default or not, but in `dvr` async we don't have this prop (field). I hope that makes sense :)

**Comment by foxhound87** [comment]
Ok, you want to use different field props to validate it. This is already scheduled for future updates.
