### ISSUE TITLE
Mobx form value does not refelect the Default value of Input Element

### ISSUE THREAD

**Issue by esakkik** [foxhound87/mobx-ajv-form#335]
```javascript
<input defaultValue="Name" onChange={form.$('name').onChange} />
```
The default value is not replicated in mobx form value
```javascript
form.$('name').value
```

**Comment by foxhound87** [comment]
The `defaultValue` prop is not supported because the package has already its internal system to handle `initial` and `default` values.

The `initial` and `default` values have to be defined in the **field definitions**.

Check the documentation for more info.

[Defining Fields](https://foxhound87.github.io/mobx-react-form/docs/fields/defining-fields.html)
[Field Properties](https://foxhound87.github.io/mobx-react-form/docs/api-reference/fields-properties.html)

**Comment by foxhound87** [comment]
I'm sorry but I just noticed that I forgot to document the use of the `initial` property on the documentation. I will fix it asap!

**Comment by foxhound87** [comment]
@ezk2410  can you check if the latest version fixes your issue?
