### ISSUE TITLE
When enable useStrict=true in mobx, mobx-react-form got error 

### ISSUE THREAD

**Issue by augustine-tran** [foxhound87/mobx-ajv-form#38]
`this.validator.genericErrorMessage = null;` this line of cod will raise this error 

> Uncaught Error: [mobx] Invariant failed: It is not allowed to create or change state outside an `action` when MobX is in strict mode. Wrap the current method in `action` if this state change is intended

I work around for now by commenting this line.

**Comment by foxhound87** [comment]
Hi @rualatngua, It's strange because the strict mode is already enabled and I don't get this error.

Anyway this should fix your issue: https://github.com/foxhound87/mobx-react-form/commit/cd101d50bb8b6659d2a040125a150d0b245f246c

Install the [v1.11.12](https://github.com/foxhound87/mobx-react-form/releases/tag/v1.11.12)
and let me know if it's ok now.

Thanks for reporting this.

**Comment by foxhound87** [comment]
Fixed https://github.com/foxhound87/mobx-react-form/commit/dd5ab02a8f58aa0f35bbfcc2ca73bb8b6bde8815#diff-1fdf421c05c1140f6d71444ea2b27638R9
