### ISSUE TITLE
What is the best way to call external library and update some stores in the app?

### ISSUE THREAD

**Issue by alexofob** [foxhound87/mobx-ajv-form#43]
@foxhound87, 

I am applying this library to handle form authentication in my app.
On successful validation, I want to call an external library (auth0) to handle authentication and update state in some UI store which is part of my application.

What is the best way to handle this? I am thinking that I should be able to call the auth0 API and the store update function in the onSuccess event handler. In this case how do I pass the auth0 library and the UIStore into the form class? Or there better approach than what I am thinking?

Thanks.

**Comment by foxhound87** [comment]
It depends on how you want to structure your app, and how you deal with the stores.

Using MobX, my approach is to create a file for each form in a `form` folder.

I don't initialize the Form into the app Stores, In this manner I can keep the form state separated from the rest of the app state so that will not pollute the initial state when doing server-side-rendering hydration.

In each file I extend the form as I need, for example chaining some actions into the `onSuccess/onError` methods: https://github.com/foxhound87/rfx-stack/blob/master/src/shared/forms/auth.js#L5

As you are not forced to extend the class, another option is to pass the form to the store and call the validation function manually: 

``` javascript
import authFrom from './AuthForm';

class AuthStore {

  login() {

    authForm.validate()
      .then((isValid) => {

        if (isValid) {
          const values = authForm.values();
          // do login stuff        
        }
      });
  }
}
```

or you can simply pass both the app Store and the Form into your react components and create handlers there.

Look here for the details on the validation function: [Form Actions: Validate the Form](https://github.com/foxhound87/mobx-react-form/blob/master/docs/FormActions.md#validate-the-form)

**Comment by foxhound87** [comment]
Or if you want leave the form to call the validation automatically without extending the class, you can setup an object with the events handlers: [Decopling the Events Handlers from the Form object](https://github.com/foxhound87/mobx-react-form/blob/master/docs/FormEvents.md#decopling-the-events-handlers-from-the-form-object)

**Comment by alexofob** [comment]
Many thanks @foxhound87 . I went with the option of importing my dependencies and extending the forms with the onSuccess events as in your boilerplate example and it works greats.
