### ISSUE TITLE
Pass Form Instance when extending validators.

### ISSUE THREAD

**Issue by haThaiHoang** [foxhound87/mobx-ajv-form#440]
Can DVR Validation custom a rule like "shouldBeEqualTo" in this example [https://foxhound87.github.io/mobx-react-form/docs/validation/modes/vjf-custom.html] ?
Because in Custom DVR, I don't see the "form" param pass into the function like this:
```
const rules = {
  telephone: {
    function: (value, form) => value === form.$('other_field').value,
    message: 'The :attribute is not equal with :other_field.',
  },
};
```
Is there a way to do with it?
Thank you!

**Comment by foxhound87** [comment]
I will look into it.

**Comment by haThaiHoang** [comment]
Thank you very much!

**Comment by easwee** [comment]
Having this same issue. This enhancement would be nice to have.

**Comment by sprrw** [comment]
One useful usecase for this would be post-validation data normalization and setting a field to a normalized value. It would be handy to have it inside validator, because there're usecases, when you can only know how to normalize input data after you perform some async request, the result of which determines the proper data normalization. So, then you can set a field in case validation passes to a proper value.

**Comment by foxhound87** [comment]
@sprrw can you open another issue for your case? With code examples would be better.
