### ISSUE TITLE
Responsive style of adjustment

### ISSUE THREAD

**Issue by 1160007652** [foxhound87/mobx-ajv-form#443]
Hello, I want to know how to respond to get hasError. In this way, I can effortlessly adjust the pattern according to the error.

This is what I have achieved.

onChange=field=>(e)=>{
  e.preventDefault();
  if(Form.hasError){
      this.setState(...);
  }else{
      this.setState(...);
  }
  field.onChange();
  field.validate();
}

It feels contrary to the principles of react-mobx-form. I have seen the MobX React Form copy for 2 days.

**Comment by foxhound87** [comment]
Cannot understand your code implementation and what you are trying to achieve.
I'm closing this now, but feel free to reopen with a better and cleaner code example. 

My suggestion is to not mix react `setState` with mobx-react-form because it already handles form data management, and see the documentation on the use of the event handlers and hooks.
