### ISSUE TITLE
Recent release is breaking yard upgrade

### ISSUE THREAD

**Issue by bbehling-trimble** [foxhound87/mobx-ajv-form#471]
After the recent release, yard upgrade is crashing. Error:

error node_modules/mobx-react-form: Command failed.
Exit code: 127
Command: opencollective postinstall

**Comment by yoution** [comment]
**npm install -g opencollective,** 
and then install mobx-react-form

**Comment by jkeruzec** [comment]
Why this has been added to the project ?

**Comment by foxhound87** [comment]
It’s for donating

**Comment by ijongkim** [comment]
This update has broken our build process as well. Since we are installing via package.json, we are simply going to stick with 1.35.1 until this issue is resolved.

It's not much of an issue to run this on a local machine:
> npm install -g opencollective,
> npm install mobx-react-form

But it would be greatly preferable not to have to modify our build process to install opencollective before installing the rest of our dependencies.

**Comment by mogadanez** [comment]
I cant install anything globally on  build server (  and its fail )

**Comment by snoopy1412** [comment]
install opencollective is not make sense, hope update

**Comment by RomanDrevo** [comment]
> install opencollective is not make sense, hope update

Same here

**Comment by foxhound87** [comment]
Should be ok now.
