### ISSUE TITLE
Proper usage of hidden fields?

### ISSUE THREAD

**Issue by rdgco** [foxhound87/mobx-ajv-form#509]
I am using hidden fields in my form to save id values that are not selectable by the user. I am binding the field to my form like this:

            <input type="hidden" {...form.$('client_id').bind()} />

However, the generated html form includes a text field for this field:

`<input type="text" id="client_id--21" name="client_id" label="client_id" placeholder="" value="16" style="background-image: url(&quot;data:image/png;base6...>`

This results in the field being visible and editable in the form. 

Is there a convention I should be using? The ability to bind the hidden fields is nice because then the values are included in the form.values() call which I am posting directly to the web server endpoint.

**Comment by foxhound87** [comment]
You can eventually add `type: 'hidden'` to the field definitions (when create the form instance) and remove it from the input component, it will be added by using `bind()`.
So you can control it afterward because the type will be (observable) in the store.
for example you can make it visible with: `form.$('client_id').set('type', 'text');`

**Comment by rdgco** [comment]
Thanks @foxhound87! All I needed was to add the type: 'hidden' to the field definitions, like this:

>   {
    name: 'client_id',
    label: 'client_id',
    rules: 'required|integer',
    type: 'hidden',
  },
