### ISSUE TITLE
isDirty is always true when initiating a Separated Properties with an array that has initial NULL value

### ISSUE THREAD

**Issue by r1y4h** [foxhound87/mobx-ajv-form#531]
Hi,

I am using Separated Properties with array of nested properties. I the array has initial value, the isDirty is set to true, but if the array has no initial values the isDirty is correctly set to false.

Here is a repl.it example:
[Mobx-React-Form Seperated Properties Array isDirty](https://repl.it/@r1y4h/Mobx-React-Form-Seperated-Properties-Array-isDirty)

I am already using v2.0.8

**Comment by r1y4h** [comment]
I temporarily hook into individual fields `onChange` event for the meantime.

**Comment by riceyeh** [comment]
This problem has nothing to do with array.  I simplify your example as shown below. It is not an array, but it still fails. The current isDirty implementation does not work for fields (including form) having nested fields. But it should work for fields without nested fields after some bugs fixed by some pull requests from me. I privately implement isDirty-like method for fields with nested fields. Some assumptions are made in my implementation, so I do not bring it to mobx-react-form. For example, is a field dirty when some nested fields are added to it?

```javascript
describe('isDrity with inital null values', () => {
   it('', () => {
    const fields = [
      'action',
      'action.applyBy',
      'action.amount',
    ]
    const labels = {
      'action.applyBy': 'Apply By',
      'action.amount': 'Discount Amount',
    }
    const types = {
      'action.amount': 'number',
    }
    const values = {
      action: {
        applyBy: null,
        amount: null,
      }
    } 

    const $531 = new Form({fields, labels, types, values}, {name: 'Form 531', options:{fallback: false}})
    expect($531.$('action.applyBy').isDirty).to.be.false
    expect($531.$('action.amount').isDirty).to.be.false
    expect($531.$('action').isDirty).to.be.false // fails
    expect($531.isDirty).to.be.false // fails
  })
});
```

**Comment by r1y4h** [comment]
hi @riceyeh 

Thank you. In unified, IsDirty works fine but I guess there's no nested field yet.
When adding a new field I think IsDirty should remain false when there's no user change before and after the creation of new field.

**Comment by r1y4h** [comment]
I need IsDirty to work for nested fields. For now, I hook to every field's onChange event as a workaround

**Comment by foxhound87** [comment]
@riceyeh can you share your solution or make a PR?

**Comment by foxhound87** [comment]
created a test, this is happening only when defining null values
