### ISSUE TITLE
.value is empty string for array / nested field

### ISSUE THREAD

**Issue by leesiongchan** [foxhound87/mobx-ajv-form#97]
``` javascript
const fields = {
  club: 'HELLO',
  members: [{
    firstname: 'Clint',
    lastname: 'Eastwood',
    hobbies: ['Soccer', 'Baseball'],
  }, {
    firstname: 'Charlie',
    lastname: 'Chaplin',
    hobbies: ['Golf', 'Basket'],
  }],
};

...

// Get Charlie's hobbies
console.log(form.$('members[1].hobbies').value) // output: ""
console.log(form.$('members[1].hobbies').values() // output: ["Golf", "Basket"]
```

**Comment by foxhound87** [comment]
It is by default correct, because that field behaves like a "fields container" and as a real field at the same time, so you can give it its own value, label or other props.

Instead `values()` will get all the nested fields of a container.

I could change the behavior of the computed `value` to be like `values()` but I'm not sure, have to think about it more.

**Comment by foxhound87** [comment]
What about a `values` computed for "field containers" instead of `value` ?

**Comment by leesiongchan** [comment]
I think so, but why not `value`? Wouldn't it be good to make it consistent?
